- name: configure {{ component }} Server
  hosts: "{{ component }}"
  vars_files:
  - credentials.yaml
  become: yes
  roles:
  - "{{ component }}"

# ansible-playbook main.yaml -e component=db
# ansible-playbook main.yaml -e component=backend
# ansible-playbook main.yaml -e component=frontend